# .github/workflows/main.yml

# Workflow name
name: "Publishing popoyoko-ui-vite"

# Event for the workflow
on:
  push:
    branches:
      - feat/ci

# List of jobs
jobs:
  gh-pages-deployment:
    # Operating System
    runs-on:
      ubuntu-latest
      # Job steps
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: npm install
      - name: Build page
        run: npm run build
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./dist
